// <auto-generated />
using System;
using Club_Proyect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Club_Proyect.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201216174059_p")]
    partial class p
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Club_Proyect.Entities.Bufet", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Horario");

                    b.Property<Guid?>("clienteID");

                    b.Property<Guid?>("ventaID");

                    b.HasKey("ID");

                    b.HasIndex("clienteID");

                    b.HasIndex("ventaID");

                    b.ToTable("Bufet");
                });

            modelBuilder.Entity("Club_Proyect.Entities.Deporte", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Activo");

                    b.Property<string>("Descripcion");

                    b.Property<string>("Nombre");

                    b.HasKey("ID");

                    b.ToTable("Deporte");
                });

            modelBuilder.Entity("Club_Proyect.Entities.Productos", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Costo");

                    b.Property<double>("Ganancia");

                    b.Property<double>("Impuesto");

                    b.Property<string>("Nombre");

                    b.Property<int>("Stock");

                    b.HasKey("ID");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Club_Proyect.Entities.Vecino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo");

                    b.Property<string>("Nombre");

                    b.Property<Guid?>("personaID");

                    b.Property<string>("telefono");

                    b.HasKey("Id");

                    b.HasIndex("personaID");

                    b.ToTable("Vecino");
                });

            modelBuilder.Entity("Club_Proyect.Entities.Venta", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("ActivooNo");

                    b.Property<DateTime>("Fecha");

                    b.Property<double>("Renta");

                    b.Property<string>("metodoPago");

                    b.Property<Guid?>("productosID");

                    b.Property<double>("totalVenta");

                    b.HasKey("ID");

                    b.HasIndex("productosID");

                    b.ToTable("Venta");
                });

            modelBuilder.Entity("Club_Proyect.Entities.horario_Deporte", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Activo");

                    b.Property<string>("Descripcion");

                    b.Property<string>("Nombre");

                    b.Property<int>("cantidad_Socios");

                    b.Property<Guid?>("deporteID");

                    b.Property<Guid?>("socioID");

                    b.HasKey("ID");

                    b.HasIndex("deporteID");

                    b.HasIndex("socioID");

                    b.ToTable("horario_Deporte");
                });

            modelBuilder.Entity("Club_Proyect.Entity.Cliente", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Activo_oNo");

                    b.Property<int>("Num_Cliente");

                    b.Property<double>("Saldo");

                    b.Property<Guid?>("personaID");

                    b.HasKey("ID");

                    b.HasIndex("personaID");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Club_Proyect.Entity.Empleado", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Activo_oNo");

                    b.Property<DateTime>("Fecha_Inicio");

                    b.Property<int>("Num_Legajo");

                    b.Property<string>("Sector");

                    b.Property<Guid?>("personaID");

                    b.HasKey("ID");

                    b.HasIndex("personaID");

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("Club_Proyect.Entity.Persona", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Activo");

                    b.Property<string>("Apellido");

                    b.Property<int>("DNI");

                    b.Property<string>("Direccion");

                    b.Property<DateTime>("FechaNacimiento");

                    b.Property<string>("Nombre");

                    b.HasKey("ID");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("Club_Proyect.Entity.Socio", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("ActivoOno");

                    b.Property<int>("Categoria");

                    b.Property<DateTime>("FechaIngresoClub");

                    b.Property<int>("NumSocio");

                    b.Property<Guid?>("horario_DeporteID");

                    b.Property<Guid?>("personaID");

                    b.HasKey("ID");

                    b.HasIndex("horario_DeporteID");

                    b.HasIndex("personaID");

                    b.ToTable("Socio");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Club_Proyect.Entities.Bufet", b =>
                {
                    b.HasOne("Club_Proyect.Entity.Cliente", "cliente")
                        .WithMany()
                        .HasForeignKey("clienteID");

                    b.HasOne("Club_Proyect.Entities.Venta", "venta")
                        .WithMany()
                        .HasForeignKey("ventaID");
                });

            modelBuilder.Entity("Club_Proyect.Entities.Vecino", b =>
                {
                    b.HasOne("Club_Proyect.Entity.Persona", "persona")
                        .WithMany()
                        .HasForeignKey("personaID");
                });

            modelBuilder.Entity("Club_Proyect.Entities.Venta", b =>
                {
                    b.HasOne("Club_Proyect.Entities.Productos", "productos")
                        .WithMany()
                        .HasForeignKey("productosID");
                });

            modelBuilder.Entity("Club_Proyect.Entities.horario_Deporte", b =>
                {
                    b.HasOne("Club_Proyect.Entities.Deporte", "deporte")
                        .WithMany()
                        .HasForeignKey("deporteID");

                    b.HasOne("Club_Proyect.Entity.Socio", "socio")
                        .WithMany()
                        .HasForeignKey("socioID");
                });

            modelBuilder.Entity("Club_Proyect.Entity.Cliente", b =>
                {
                    b.HasOne("Club_Proyect.Entity.Persona", "persona")
                        .WithMany()
                        .HasForeignKey("personaID");
                });

            modelBuilder.Entity("Club_Proyect.Entity.Empleado", b =>
                {
                    b.HasOne("Club_Proyect.Entity.Persona", "persona")
                        .WithMany()
                        .HasForeignKey("personaID");
                });

            modelBuilder.Entity("Club_Proyect.Entity.Socio", b =>
                {
                    b.HasOne("Club_Proyect.Entities.horario_Deporte")
                        .WithMany("socios")
                        .HasForeignKey("horario_DeporteID");

                    b.HasOne("Club_Proyect.Entity.Persona", "persona")
                        .WithMany()
                        .HasForeignKey("personaID");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
